### ISSUE TITLE
[SDKCLI-32] npx @saagie/sdk init

### ISSUE THREAD

**Issue by yoannfleurydev** [saagie/sdk#56]
**Describe the bug**
The program works, but there is a strange stack trace in the terminal.

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**

```
npx @Saagie/sdk init                                                                                                          Mer 27 mai 11:05:59 2020
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/<user>/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/14.3.0/bin/node" "/Users/<user>/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/<user>/.npm/_npx/57445/lib/node_modules/@saagie/sdk/node_modules/fsevents
gyp ERR! node -v v14.3.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by yoannfleurydev** [comment]
No more errors when uninstalling and re-installing XCode.
